apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: xx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: myappcontainer
        image: pyxida/myapp:v1.0.0
        ports:
        - containerPort: 8080
        envs:
        - name: namespace
          valueFrom: 
            fieldRef:
              fieldPath: metadata.namespace  
